CREATE TABLE parcelas (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(100) NOT NULL,
    latitud    DOUBLE PRECISION NOT NULL,
    longitud   DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lecturas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcela_id    BIGINT NOT NULL,
    humedad       DOUBLE PRECISION,
    temperatura   DOUBLE PRECISION,
    precipitacion DOUBLE PRECISION,
    fecha         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lectura_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas(id)
);

CREATE TABLE recomendaciones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcela_id  BIGINT NOT NULL,
    nivel_riego DOUBLE PRECISION,
    descripcion VARCHAR(255),
    fecha       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recomendacion_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas(id)
);